[package]

edition = "2021"

name = "l3vm"
version = "0.0.1"

[dependencies]
either = "1.6.1"
unfold = "0.2.0"
log = "0.4"
env_logger = "0.9.0"

[features]
benchmark = []

[profile.release]
debug = 1

